### ISSUE TITLE
Please linux support

### ISSUE THREAD

**Issue by HidemaruOwO** [tsukumijima/Real-ESRGAN-GUI#13]
Thank you for developing this tool
I would like to use this tool on Linux as well!!

**Comment by tsukumijima** [comment]
This app is a wrapper app to enable non-technical people to use Real-ESRGAN-ncnn-vulkan.
I'm sorry, but due to lack of motivation to work on this project, lack of demand for a Linux version, and the fact that the Linux version of Flutter Desktop is not as well supported as the Windows and Mac versions to begin with, I do not plan to support it. Thank you for your understanding.

**Comment by HidemaruOwO** [comment]
I see.
Good luck with the development!
